[[tasks]]
name = "dcupb"
command = "docker compose up --build"
description = "KarimadoWeb: Launch a preconfigured Vue development container"

[[tasks]]
name = "dcsh"
command = "docker compose exec nodedev {{ getvar_or_default 'CLI_ARGS' 'bash' }}"
description = "KarimadoWeb: Exec a command in the Vue development container"
